### Metadata ###
openapi: '3.0.0'
info:
  title: 'Flow API Report Service'
  description: 'An API for tracking public transit routes and crowdsourcing reports'
  version: '1.0.0'

### Server ###
servers:
  - url: placeholder

### Endpoints ###
paths:
  # admin-only
  /reports:
    get:
      description: Get all reports
    delete:
      description: Delete all reports

  /report:
    get:
      description: Get a report
    post:
      description: Post a report
    patch:
      description: Update a report
    delete:
      description: Delete a report

### Schemas ###
components:
  schemas:
    Report:
