### Metadata ###
openapi: '3.0.0'
info:
  title: 'Flow API Route Service'
  description: 'An API for tracking public transit routes and crowdsourcing reports'
  version: '1.0.0'

### Server ###
servers:
  - url: 'https://www.example.com'

### Endpoints ###
paths:
  /routes:
    get:
      description: Get all routes
      responses:
        '200':
          description: Successfully retrieved routes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'

    post:
      description: Create a new route
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Route'
      responses:
        '200':
          description: Successfully created route
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'
    
    delete:
      description: Delete all routes
      responses:
        '200':
          description: Successfully deleted routes
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'

  /routes/{id}:
    parameters:
      - name: id
        description: The unique identifier of a route
        in: path
        required: true
        schema:
          type: string

    get:
      description: Get a route
      responses:
        '200':
          description: Successfully retrieved route
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'

    patch:
      description: Update a route
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                stops:
                  type: array
                  items:
                    type: string
                active:
                  type: boolean
      responses:
        '200':
          description: Successfully updated route
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'
    
    delete:
      description: Delete a route
      responses:
        '200':
          description: Successfully deleted route
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'

### Components ###
components:
  
  ### Responses ###
  responses:
    400Error:
      description: Invalid client request.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                description: A human-readable error message.
                type: string

    500Error:
      description: The server encountered an error.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                description: A human-readable error message.
                type: string

  ### Schemas ###
  schemas:
    Route:
      description: A public transit route tracked by Flow
      type: object
      required:
        - id
        - name
        - stops
      properties:
        id:
          type: string
        name:
          type: string
        stops:
          type: array
          items:
            type: string
        createdBy:
          type: string
          description: ID of the user who created the route
        active:
          type: boolean
          default: true