name: Test Report Service

on:
  push:
    paths:
      - 'services/report/**'
      - '.github/workflows/report_test.yml'
  pull_request:
    paths:
      - 'services/report/**'
      - '.github/workflows/report_test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/report

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest